version: "3.6"

services:
  keycloak:
    container_name: keycloakPython
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    ports:
      - 8080:8080

networks:
  web:
