version: '3.9'

services:
  postgresql:
    container_name: postgresql_discourse
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
    networks:
      - discourse-network


  redis:
    container_name: redis_discourse
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
      - discourse-network

  discourse:
    container_name: discourse
    image: docker.io/bitnami/discourse:3.1.3
    ports:
      - 3000
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=[HERE_YOUR_DOMAIN]
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - DISCOURSE_EMAIL=[HERE_ADMIN_EMAIL]
      - DISCOURSE_USERNAME=[HERE_ADMIN_USERNAME]
      - DISCOURSE_PASSWORD=[HERE_ADMIN_PASSWORD]
      - DISCOURSE_SMTP_HOST=[HERE_SMTP_HOST]
      - DISCOURSE_SMTP_PORT=[HERE_SMTP_PORT]
      - DISCOURSE_SMTP_USER=[HERE_SMTP_USER]
      - DISCOURSE_SMTP_PASSWORD=[HERE_SMTP_PASSWORD]
      - DISCOURSE_SMTP_PROTOCOL=[HERE_SMTP_PROTOCOL]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.discourse.entrypoints=websecure"
      - "traefik.http.routers.discourse.tls.certresolver=letsencrypt"
      - "traefik.http.routers.discourse.tls=true"
      - "traefik.http.services.discourse.loadbalancer.server.port=3000"
      - "traefik.http.routers.discourse.rule=Host(`[HERE_YOUR_DOMAIN]`)"
    networks:
      - discourse-network
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  sidekiq:
    container_name: sidekiq_discourse
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=[HERE_YOUR_DOMAIN]
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
    networks:
      - discourse-network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

networks:
  discourse-network:
    external: true
