site_name: GREENGAGE Documentation
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
extra_javascript:
  - javascripts/custom.js
extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Guidelines: guidelines
  - Tools:
      - Backbone:
        - Keycloak:
          - Description: tools/keycloak
          - Integration: tools/keycloak/integration
          - Examples:
              - Node: tools/keycloak/examples#nodejs
              - Python: tools/keycloak/examples#python
      - Community and Co-production process Management: 
        - Wordpress:
            - Description: tools/wordpress
            - Integration: tools/wordpress/integration
            - Example of deployment: tools/wordpress/examples
        - Discourse:
          - Description: tools/Discourse
          - Integration: tools/Discourse/integration
          - Example of deployment: tools/Discourse/examples
        - Collaborative Environment:
          - Description: tools/collaborativeEnvironment
          - Usage: tools/collaborativeEnvironment/integration
          - Example of deployment: tools/collaborativeEnvironment/examples
      - Data crowdsourcing and capture: 
        - MODE:
            - Description: tools/mode
            - Integration: tools/mode/integration
            - Examples:
                - iOS: tools/mode/examples/ios
                - Android: tools/mode/examples/android
                - Backend: tools/mode/examples/backend
        - Libelium sensor integration:
            - Description: tools/sensorsIntegration
            - Integration: tools/sensorsIntegration/integration
      - Data analysis and insights generation:
        - UrbanTEP / VISAT:
          - Description: tools/urbantep-visat
          - Deployment: tools/urbantep-visat/deployment
          - Integration: tools/urbantep-visat/integration
          - Example: tools/urbantep-visat/examples
        - DataHub:
            - Description: tools/datahub
            - Usage: tools/datahub/usage
            - Example of integration: tools/datahub/examples
        - Apache Superset:
            - Description: tools/superset
            - Usage: tools/superset/usage
            - Example of integration: tools/superset/examples
locale:
  - en
