site_name: GREENGAGE Documentation
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
extra_javascript:
  - javascripts/custom.js
extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Guidelines: guidelines
  - Tools:
      - Keycloak:
          - Description: tools/keycloak
          - Integration: tools/keycloak/integration
          - Examples:
              - Node: tools/keycloak/examples#nodejs
              - Python: tools/keycloak/examples#python
      - Collaborative Environment:
          - Description: tools/collaborativeEnvironment
          - Integration: tools/collaborativeEnvironment/integration
          - Example of deployment: tools/collaborativeEnvironment/examples

locale:
  - en
