site_name: Greengage Documentation
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - Home: index.md
  - Guidelines: guidelines
  - Tools:
      - Keycloak:
          - Description: tools/keycloak
          - Integration: tools/keycloak/integration
          - Example: tools/keycloak/example
locale:
  - en
